repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: local
    hooks:
      - id: rust-linting
        name: Rust linting
        description: Run cargo fmt on files included in the commit.
        entry: cargo fmt --all --
        pass_filenames: true
        types:
          - file
          - rust
        language: system
      - id: rust-clippy
        name: Rust clippy
        description: Run cargo clippy on files included in the commit.
        entry: 'cargo clippy --all-targets --all-features -- -Dclippy::all'
        pass_filenames: false
        types:
          - file
          - rust
        language: system
